# Generated by Django 5.2 on 2025-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_totalprofit_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='box_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Boxes'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cost_per_box',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost per Box'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost per Item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cost_per_package',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost per Package'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expire Date'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='items_per_package',
            field=models.IntegerField(default=0, verbose_name='Items per Package'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='packages_per_box',
            field=models.IntegerField(default=0, verbose_name='Packages per Box'),
        ),
    ]
