# Generated by Django 5.2 on 2025-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_purchase_quantity_remove_purchase_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cost_per_box',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Box'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_per_package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Package'),
        ),
    ]
