# Generated by Django 5.2 on 2025-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_purchase_cost_per_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='box_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Boxes'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Cost per Item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='items_per_package',
            field=models.IntegerField(blank=True, verbose_name='Items per Package'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='packages_per_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Packages per Box'),
        ),
    ]
