# Generated by Django 5.2 on 2025-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_purchase_box_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='box_quantity',
            field=models.IntegerField(default=0, verbose_name='Number of Boxes'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='items_per_package',
            field=models.IntegerField(default=0, verbose_name='Items per Package'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='packages_per_box',
            field=models.IntegerField(default=0, verbose_name='Packages per Box'),
        ),
    ]
