# Generated by Django 5.2 on 2025-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchase_total_cost_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_cost_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Cost'),
        ),
    ]
