# Generated by Django 5.2 on 2025-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_purchase_total_cost_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Report Date')),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Purchases')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Sales')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Profit')),
                ('report_data', models.JSONField(verbose_name='Detailed Report Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
            },
        ),
    ]
