# Generated by Django 5.2 on 2025-04-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report_data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
