# Generated by Django 5.2 on 2025-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_monthlyreport_delete_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='box_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Boxes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='items_per_package',
            field=models.IntegerField(blank=True, null=True, verbose_name='Items per Package'),
        ),
        migrations.AddField(
            model_name='sale',
            name='packages_per_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Packages per Box'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price_per_box',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price per Box'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price per Item'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price_per_package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price per Package'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Amount'),
        ),
    ]
