# Generated by Django 5.2 on 2025-05-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_sale_box_quantity_sale_items_per_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='box_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='items_per_package',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='packages_per_box',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price_per_box',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price_per_item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price_per_package',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='box_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Boxes'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_per_box',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Box'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Item'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_per_package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Package'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='items_per_package',
            field=models.IntegerField(blank=True, null=True, verbose_name='Items per Package'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='packages_per_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Packages per Box'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_cost_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale'),
        ),
    ]
