# Generated by Django 5.2 on 2025-05-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_saleitem_total_cost_value_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total_cost_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Cost'),
        ),
    ]
